role :web, "r2a7"

set :user, 'apps'

namespace :deploy do
  desc "deploy the widget"
  task :default do
    puts "cap is here too #{$$}"
    STDERR.puts "cappy err"
    sleep 2
    run "ls"
    #raise "foobar"
  end
  
  desc "refine the widgets"
  task :refine do
  end
  
  task :clandestine do
  end
end